query Partner($locale: SiteLocale) {
	partner(locale: $locale, fallbackLocales: [sv]) {
		...PartnerFragment
	}
}

fragment PartnerFragment on PartnerRecord {
	examples {
		... on PartnerBlockRecord {
			logo {
				...ImageFragment
			}
		}
	}
	title
}
