query Product($slug: String, $locale: SiteLocale) {
	product(locale: $locale, fallbackLocales: [sv], filter: { slug: { eq: $slug } }) {
		...ProductFragment
	}
}

query AllProducts($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allProducts(first: $first, skip: $skip, locale: $locale, fallbackLocales: [sv]) {
		...ProductFragment
	}
	_allProductsMeta {
		count
	}
}

fragment ProductFragment on ProductRecord {
	id
	image {
		...ImageFragment
	}
	layout {
		__typename
		... on TwoColumnRecord {
			columns {
				... on ColumnRecord {
					color
					image {
						...ImageFragment
					}
				}
				text {
					blocks
					links
					value
				}
			}
		}
		... on TextAndImageRecord {
			color
			layout
			media {
				...MediaFragment
			}
			text {
				blocks
				links
				value
			}
		}
		... on CtaRecord {
			id
			text {
				blocks
				links
				value
			}
		}
	}
	title
	slug
}

fragment ProductLightFragment on ProductRecord {
	image {
		...ImageFragment
	}
	layout {
		__typename
		... on TwoColumnRecord {
			columns {
				... on ColumnRecord {
					color
					image {
						...ImageFragment
					}
					text {
						blocks
						links
						value
					}
				}
			}
		}
		... on TextAndImageRecord {
			color
			layout
			media {
				...MediaFragment
			}
			text {
				blocks
				links
				value
			}
		}
	}
	title
	slug
}
