query Product($slug: String, $locale: SiteLocale) {
	product(locale: $locale, fallbackLocales: [sv], filter: { slug: { eq: $slug } }) {
		...ProductFragment
	}
}

query AllProducts($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allProducts(first: $first, skip: $skip, locale: $locale, fallbackLocales: [sv]) {
		...ProductFragment
	}
	_allProductsMeta {
		count
	}
}

fragment ProductFragment on ProductRecord {
	id
	intro {
		blocks
		links
		value
	}
	image {
		...ImageFragment
	}
	thumb {
		...ImageFragment
	}
	category {
		...ProductCategoryFragment
	}
	productType {
		id
		title
		slug
	}
	forIndividuals
	layout {
		__typename
		... on TwoColumnRecord {
			id
			columns {
				... on ColumnRecord {
					color
					image {
						...ImageFragment
					}
				}
				text {
					blocks
					links
					value
				}
			}
		}
		... on TextAndImageRecord {
			id
			color
			layout
			media {
				...MediaFragment
			}
			content {
				blocks {
					__typename
					... on ToggleTextRecord {
						id
						headline
						text {
							blocks
							links
							value
						}
					}
				}
				links
				value
			}
		}
		... on CtaRecord {
			id
			text {
				blocks
				links
				value
			}
		}
		... on ToggleTextRecord {
			id
			headline
			text {
				blocks
				links
				value
			}
		}
	}
	title
	slug
	seo {
		title
		description
	}
}

fragment ProductLightFragment on ProductRecord {
	image {
		...ImageFragment
	}
	thumb {
		...ImageFragment
	}
	productType {
		id
		title
		slug
	}
	forIndividuals
	layout {
		__typename
		... on TwoColumnRecord {
			columns {
				... on ColumnRecord {
					color
					image {
						...ImageFragment
					}
					text {
						blocks
						links
						value
					}
				}
			}
		}
		... on TextAndImageRecord {
			color
			layout
			media {
				...MediaFragment
			}
			content {
				blocks {
					... on ToggleTextRecord {
						id
						headline
						text {
							blocks
							links
							value
						}
					}
				}
				links
				value
			}
		}
	}
	title
	slug
	seo {
		title
		description
	}
}
