query Reference($locale: SiteLocale) {
	reference(locale: $locale, fallbackLocales: [sv]) {
		...ReferenceFragment
	}
}

fragment ReferenceFragment on ReferenceRecord {
	examples {
		... on ReferenceBlockRecord {
			image {
				...ImageFragment
			}
			link
			logo {
				...ImageFragment
			}
			title
			text {
				blocks
				links
				value
			}
		}
	}
	title
	intro {
		blocks
		links
		value
	}
}
