query Start($locale: SiteLocale) {
	start(locale: $locale, fallbackLocales: [sv]) {
		...StartFragment
	}
}

fragment StartFragment on StartRecord {
	android
	film {
		...VideoFragment
	}
	filmText {
		... on TextRecord {
			text
		}
	}
	image {
		...ImageFragment
	}
	ios
	news {
		... on NewsBlockRecord {
			url
			text
		}
	}
	faqText {
		blocks {
			__typename
			... on ToggleTextRecord {
				id
				headline
				text {
					blocks
					links
					value
				}
			}
		}
		links
		value
	}
	shortcut {
		... on ShortcutRecord {
			__typename
			id
			color
			text {
				blocks
				links
				value
			}
			image {
				...ImageFragment
			}
			link {
				__typename
				... on AboutRecord {
					image {
						...ImageFragment
					}
					text {
						value
						links
						blocks {
							... on LinkTextRecord {
								text
								url
							}
						}
					}
					title
					url
				}
				... on ProductRecord {
					image {
						...ImageFragment
					}
					layout {
						... on TwoColumnRecord {
							columns {
								... on ColumnRecord {
									color
									image {
										...ImageFragment
									}
								}
							}
						}
						... on TextAndImageRecord {
							color
							layout
							media {
								...MediaFragment
							}
						}
					}
					title
				}
				... on SupportStartRecord {
					title
				}
				... on PartnerRecord {
					examples {
						... on PartnerBlockRecord {
							logo {
								...ImageFragment
							}
						}
					}
					title
				}
				... on ReferenceRecord {
					examples {
						... on ReferenceBlockRecord {
							image {
								...ImageFragment
							}
							link
							logo {
								...ImageFragment
							}
							title
						}
					}
					title
				}
			}
		}
	}
	textApp
	title
	logos {
		...FileFragment
	}
	seo {
		title
		description
	}
}
