query Support($locale: SiteLocale) {
	support(locale: $locale, fallbackLocales: [sv]) {
		...SupportFragment
	}
}

query AllSupports($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allSupports(first: $first, skip: $skip, locale: $locale, fallbackLocales: [sv]) {
		...SupportFragment
	}
	_allSupportsMeta {
		count
	}
}

fragment SupportFragment on SupportRecord {
	sections {
		... on SectionRecord {
			id
			title
			text {
				blocks
				links
				value
			}
			slug
		}
	}
	id
	title
	slug
}

fragment SupportLightFragment on SupportRecord {
	sections {
		... on SectionRecord {
			id
			title
			text {
				blocks
				links
				value
			}
			slug
		}
	}
	id
	title
	slug
}
