query Support($locale: SiteLocale) {
	support(locale: $locale, fallbackLocales: [sv]) {
		...SupportFragment
	}
}

query AllSupports($first: IntType = 500, $skip: IntType = 0, $locale: SiteLocale) {
	allSupports(first: $first, skip: $skip, locale: $locale, fallbackLocales: [sv]) {
		...SupportFragment
	}
	_allSupportsMeta {
		count
	}
}

fragment SupportFragment on SupportRecord {
	section {
		... on SectionRecord {
			title
		}
	}
	title
}

fragment SupportLightFragment on SupportRecord {
	section {
		... on SectionRecord {
			title
		}
	}
	title
}
